version: '3'

services:


  selenoid:
    image: aerokube/selenoid:latest
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./browsers.json:/etc/selenoid/browsers.json
      - /opt/selenoid/video:/opt/selenoid/video
    restart: always

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    container_name: selenoid-ui
    ports:
      - "8090:8090"
    networks:
      - selenoid
    command: [ "--selenoid-uri", "http://selenoid:4444", "-listen", ":8090" ]
    restart: always


networks:
  selenoid:
    name: selenoid
    external: true
